apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lsoj
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0077-tenant/ci1t-830-0077-app/devfile-sample-lsoj@sha256:2c69028d889992efddb450c6ada59ab4326278d14d42a55884e8061eaedc5e05
        name: my-nodejs
        resources: {}
status: {}
